variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - lint

gitleaks:
  stage: lint
  image:
    name: mega-docker.artifactory.developers.mega.co.nz:8443/gitleaks:v8.18.2-mega-1.0
    entrypoint: [""]
  script:
    - gitleaks detect -v --redact -c .gitleaks/gitleaks.toml

clang-format:
  stage: lint
  script:
    - echo "Run clang-format"
