variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - lint

gitleaks:
  stage: lint
  image:
    name: mega-docker.artifactory.developers.mega.co.nz:8443/gitleaks:v8.18.2-mega-1.0
    entrypoint: [""]
  script:
    - gitleaks detect -v --redact -c .gitleaks/gitleaks.toml

clang-format:
  stage: lint
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y git clang-format
  script:
    - git clang-format
